#!/bin/sh
which php > /dev/null
if [ $? -eq 1 ]; then echo "apt-get install php5-cli"; exit 1; fi
which perl > /dev/null
if [ $? -eq 1 ]; then echo "apt-get install perl"; exit 1;fi

php -f dontletyourdreamsbedreams.php -- --test > /dev/null
if [ $? -eq 1 ]; then exit 1; fi

php -f dontletyourdreamsbedreams.php | ./Markdown.pl > yesterdayyousaidtomorrow.html
if [ ! -s $DISPLAY ]; then
    which x-www-browser > /dev/null
    if [ $? -eq 0 ]; then 
        x-www-browser yesterdayyousaidtomorrow.html 2>/dev/null 1>/dev/null &
        exit 0
    fi
else
    which www-browser > /dev/null
    if [ $? -eq 0 ]; then 
        www-browser yesterdayyousaidtomorrow.html
        exit 0
    fi
fi

echo "open yesterdayyousaidtomorrow.html in your favorite browser you hipster fuck"
